[package]
name = "middle-screenshot"
version = "0.2.3"
edition = "2024"
exclude = [
    "*.traineddata",
    "*.ico",
    "*.log",
]

[package.metadata.vcpkg]
branch = "master"
dependencies = [
    "leptonica",
    "tesseract",
]
git = "https://github.com/microsoft/vcpkg"

[package.metadata.vcpkg.target.x86_64-pc-windows-msvc]
triplet = "x64-windows-static-md"

[dependencies]
anyhow = "1.0.102"
clipboard-win = "5.4.1"
egui_extras = "0.34.3"
imageproc = "0.27.0"
lazy_static = "1.5.0"
leptess = "0.14.0"
log-error = "0.1.2"
screenshots = "0.8.10"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tray-item = "0.10.0"

[dependencies.eframe]
features = ["wgpu"]
version = "0.34.3"

[dependencies.image]
default-features = false
features = [
    "bmp",
    "tiff",
    "ico",
]
version = "0.25.10"

[dependencies.rdev]
features = ["unstable_grab"]
version = "0.5.3"

[dependencies.time]
features = [
    "std",
    "macros",
]
version = "0.3.47"

[dependencies.tracing-subscriber]
features = [
    "fmt",
    "local-time",
    "env-filter",
]
version = "0.3.23"

[target."cfg(windows)".build-dependencies]
windres = "0.2"
