name: "publish"

on:
  push:
    tags:
      - v*

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-rust:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg

      - name: Vcpkg install
        run: cargo vcpkg build

      - name: Build
        run: cargo build --verbose --release

      - name: Move target
        run: mv target\release\middle-screenshot.exe .

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'middle_screenshot.zip'
          path: 'chi_sim.traineddata chi_sim_vert.traineddata eng.traineddata middle-screenshot.ico middle-screenshot.exe'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: "middle_screenshot.zip"
