name: "publish"

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install cargo-vcpkg
        run: cargo install cargo-vcpkg

      - name: vcpkg install
        run: cargo vcpkg build

      - name: Build
        run: cargo build --verbose --release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'middle_screenshot-${GITHUB_REF#refs/tags/}-${{ matrix.target }}.zip'
          path: 'chi_sim.traineddata chi_sim_vert.traineddata eng.traineddata middle-screenshot.ico target\release\middle-screenshot.exe'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "middle_screenshot-${GITHUB_REF#refs/tags/}-${{ matrix.target }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
